### ISSUE TITLE
Is the Waveshare RP2040-ETH Mini supported?

### ISSUE THREAD

**Issue by chron0** [maxgerhardt/platform-raspberrypi#44]
Hi, is the Waveshare RP2040-ETH Mini supported and if not, is support for it planned? It would be great to have ethernet capable rp2040s to work with esphome. See: https://www.waveshare.com/wiki/RP2040-ETH

**Comment by maxgerhardt** [comment]
Currently that board is not in the list of supported boards at https://github.com/earlephilhower/arduino-pico/tree/master#supported-boards. Please file a board request issue at https://github.com/earlephilhower/arduino-pico/issues instead of here.

Note that the absence of a specialized board definition matters an amount of absolute 0. As the Wiki says in the Arduino section, you'll be fine with just the regular "Pico" board definition and the "RP2040-ETH test demo" project as linked in their wiki should run just fine with the standard `platformio.ini`.

```ini
[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m

[env:pico]
board = pico
```
