### ISSUE TITLE
Recent change broke RP2350 FastLED build

### ISSUE THREAD

**Issue by zackees** [maxgerhardt/platform-raspberrypi#79]
Notice that these are both from the same commit in our repo, but the build fails in one and not the other. Using a specific git commit fixes the problem.

Working:

https://github.com/FastLED/FastLED/actions/runs/11067480790

Failing:

https://github.com/FastLED/FastLED/actions/runs/11075386507

**Comment by zackees** [comment]
This fixes our build for now

```python
RPI_PICO2 = Board(
    board_name="rpipico2",
    platform="https://github.com/maxgerhardt/platform-raspberrypi.git#5e87ae34ca025274df25b3303e9e9cb6c120123c",
    platform_needs_install=True,  # Install platform package to get the boards
    platform_packages="framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git",
    framework="arduino",
    board_build_core="earlephilhower",
    board_build_filesystem_size="0.5m",
)
```

**Comment by erichelgeson** [comment]
```undefined reference to `__retarget_lock_init_recursive'``` 

I get this same error in my project too. Pointing back to `5e87ae34ca025274df25b3303e9e9cb6c120123c` is a temp work around.

**Comment by maxgerhardt** [comment]
Arduino-Pico did a toolchain upgrade to GCC 14. You cannot use the old git commit hash for the platform and the bleeding edge `arduino-pico.git`. Either keep both old, or both up-to-date.

You might also need to clear your cache: https://github.com/earlephilhower/arduino-pico/pull/2491 

The upgrade to be able to compile RP2350 in RISC-V mode should be complete soon.

**Comment by zackees** [comment]
I'm not sure it's a cache thing. The builders failed and they fetch from the url on every run.

**Comment by nkinnan** [comment]
Broke esphome as well

edit:
`platform = https://github.com/maxgerhardt/platform-raspberrypi.git#5e87ae34ca025274df25b3303e9e9cb6c120123c`
worked great

**Comment by nkinnan** [comment]
@maxgerhardt Would you mind creating a tag or release periodically? Would be better to reference that directly for downstream build versioning. Also, thanks for maintaining this fork while the... disagreement is ongoing :)

**Comment by maxgerhardt** [comment]
Yes, I'm going to create tags for the ones using the previous toolchain version (as per https://github.com/maxgerhardt/platform-raspberrypi/commit/934fe156aee0cf4a5e3ef813d0b23846591fd026, last ones ver v2.2.0 from [earlephilhower/pico-quick-toolchain/releases](https://github.com/earlephilhower/pico-quick-toolchain/releases)) and the ones we use now (v4.0.0).

The same thing can be achieved right now by referencing the commits though: Last version with the old toolchain is 
```ini
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#5e87ae34ca025274df25b3303e9e9cb6c120123c
```
Toolchain updates are always going to happen, as they do now and in the future. Ideally of course, I would look this platform to be in the PIO registry to always hop from synced stable version to stable version. That is not possible as of now.

So, **extra** care must be taken that projects **do not** use bleeding edge versions of both platform and framework (Arduino-Pico) **or** bleeding edge version of the platform and a fixated older version of the framework, but fixate both versions in place. E.g.., The above commit hash with
```ini
platform_packages =
   framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git#4.0.2
```
should work perfectly fine. If you **don't** touch the `framework-arduinopico` version, but instead use only
```ini
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
```
you should be fine too, because I take care that the latest commit at the end of the day always results in a working build. Right now, the CI for this platform is running perfectly fine, with Arduino-Pico pointing at the `#riscv` branch. 

![grafik](https://github.com/user-attachments/assets/48ece991-99fb-4844-83cf-65f8cffd8860)

I'm expecting this to be merged shortly, so we will be back on mainline Arduino-Pico with RISC-V support.

**Comment by zackees** [comment]
Confirmed working.

**Comment by maxgerhardt** [comment]
FYI, platform is switched back to mainline Arduino-Pico, latest commit; So, the latest commit of this platform works again with the latest commit of Arduino-Pico *and* has added RISC-V build support ✨ ([docs](https://arduino-pico.readthedocs.io/en/latest/platformio.html#selecting-the-cpu-architecture)).

I'm also thinking about adding backwards-compatibility for building older Arduino-Pico commits, by some type of version detection.. we could select the older toolchain version automatically to still get a successful build. Since I see *major* projects like FastLED and ESPHome getting build failures from not getting the package management exactly right and running into this hickup, this might make snse.

**Comment by nkinnan** [comment]
esphome was not previously fixing platform, but is now referencing #5e87ae34ca025274df25b3303e9e9cb6c120123c directly.  In conjunction with https://github.com/earlephilhower/arduino-pico/releases/download/3.9.4/rp2040-3.9.4.zip which is currently two months old. 

Fixing the version is for sure desirable.  I'm happy to continue pointing at #5e87ae34ca025274df25b3303e9e9cb6c120123c but it might be nice to have a specific release or tag to use instead of a commit.  Not having that might be why platform wasn't fixed to a specific version previously (I don't know the history, I just came in to try to fix it now).  The last tag was over 3 years ago: https://github.com/maxgerhardt/platform-raspberrypi/tags

edit: esphome is now pointing to https://github.com/maxgerhardt/platform-raspberrypi/releases/tag/v1.2.0-gcc12 per jesserockz, thanks :)

**Comment by maxgerhardt** [comment]
Done with [v1.2.0-gcc12](https://github.com/maxgerhardt/platform-raspberrypi/releases/tag/v1.2.0-gcc12). 

Still, working on backwards compat because users should know nothing about those behind the scenes stuff.
